version: '3'

services:
  currencyapi_db:
    container_name: currencyapi_db
    image: postgres:latest
    restart: always
    env_file:
      - db.env
    ports:
      - '5432:5432'
    networks:
      - currencyapi
    volumes: 
      - db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - currencyapi
    restart: unless-stopped
  
  currencyapi:
    container_name: currencyapi_app
    build: currencyapi_app
    # restart: always
    depends_on:
      - currencyapi_db
    tty: true # terminali sürekli açık tutmak için
    env_file:
      - currencyapi_app/.env
    networks:
      - currencyapi

networks:
  currencyapi:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin:
    driver: local